# Generated by Django 5.0.7 on 2024-07-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="email контактного лица"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                ("street", models.CharField(max_length=150, verbose_name="улица")),
                ("house", models.CharField(max_length=20, verbose_name="номер дома")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="название")),
                (
                    "product_model",
                    models.CharField(max_length=250, verbose_name="модель товара"),
                ),
                (
                    "date_of_release",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="дата выхода товара на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="TradeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="название организации"
                    ),
                ),
                (
                    "link_network",
                    models.CharField(
                        choices=[
                            ("FACTORY", "завод"),
                            ("RETAIL_NETWORK", "розничная сеть"),
                            (
                                "INDIVIDUAL_ENTREPRENEUR",
                                "индивидуальный предприниматель",
                            ),
                        ],
                        max_length=150,
                        verbose_name="звено цепи",
                    ),
                ),
                (
                    "dept",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.contacts",
                        verbose_name="контакты",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.products",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.tradelink",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
            },
        ),
    ]
