# Generated by Django 5.0.7 on 2024-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradelink",
            name="dept",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=9,
                null=True,
                verbose_name="задолженность перед поставщиком",
            ),
        ),
    ]
